# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: check-format
        name: Check format
        entry: hatch run +py=3.11 check-format
        language: python
        types: [python]
        pass_filenames: true
    -   id: check-lint
        name: Check lint
        entry: hatch run +py=3.11 check-linter
        language: python
        types: [python]
        pass_filenames: true
    -   id: check-type
        name: Check types
        entry: hatch run +py=3.11 check-type
        language: python
        types: [python]
        pass_filenames: true
