site_name: mkdocs-gentags
repo_url: https://github.com/georgeyk/mkdocs-gentags
site_description: mkdocs plugin to generate tags from metadata (aka frontmatter).
site_url: https://georgeyk.github.io/mkdocs-gentags/
edit_uri: blob/main/docs/
site_author: George Y. Kussumoto
copyright: Copyright (c) 2024, George Y. Kussumoto

theme:
  name: mkdocs
  custom_dir: theme

nav:
  - Home: 'index.md'
  - Development: 'development.md'
  - Changelog: 'changelog.md'
  - Example:
    - Page 1: 'page-tag-one.md'
    - Page 2: 'page-tag-two.md'
    - Page 3: 'page-tag-multiple.md'

    - Tag 1: 'tags/one.md'
    - Tag 2: 'tags/two.md'
    - All: 'tags/index.md'

watch:
  - theme

plugins:
  - search
  - gentags:
      path: tags
      tags_index_template: tags.html
      tags_template: tag.html
      verbose: true
