name: "Docs"

on:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]
    branches: [main]

jobs:
  run:
    name: "Docs"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install hatch
      run: |
        python -m pip install hatch

    - name: Update docs
      run: hatch run +py=3.11 dev:mkdocs gh-deploy
