name: "Linters"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    name: "Linters"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install hatch
      run: |
        python -m pip install hatch

    - name: run pre-commit
      run: hatch run +py=3.11 test:pre-commit run -a -v
